[aws]
# AWS region for CloudWatch and Cost Explorer APIs
region = "us-east-1"

# OPTIONAL:
profile_name = "ec2_instance"

[metrics]
# Cloud provider metrics to monitor
instance_metrics = ["CPUUtilization", "NetworkIn", "NetworkOut"]

[system]
# Enable system metrics collection
enabled = true 

# Toggle memory metrics collection
collect_memory = true

# Toggle disk metrics collection 
collect_disk = true

# Toggle proccess metric collection
collect_processes = true
