[aws]
# AWS region for CloudWatch and Cost Explorer APIs
region = "us-east-1"

# OPTIONAL:
profile_name = "ec2_instance"

[metrics]
# Cloud provider metrics to monitor
instance_metrics = ["CPUUtilization", "NetworkIn", "NetworkOut"]
