[aws]
# AWS region for CloudWatch and Cost Explorer APIs
region = "us-east-1"

# OPTIONAL:
profile_name = "ec2_instance"

[metrics]
# How often to poll for new metrics (in seconds)
poll_interval_secs = 300

# Cloud provider metrics to monitor
instance_metrics = ["CPUUtilization", "NetworkIn", "NetworkOut"]
